LCC_TO_AREA = {
    "A": "Reference Works",
    "B": "Humanities",
    "C": "Humanities",
    "D": "Humanities",
    "E": "Humanities",
    "F": "Humanities",
    "G": "Social Sciences",
    "H": "Social Sciences",
    "J": "Social Sciences",
    "K": "Social Sciences",
    "L": "Social Sciences",
    "M": "Music and Arts",
    "N": "Music and Arts",
    # "P": "Humanities",
    "P": "Language and Literature",
    "Q": "STEM",
    "R": "Medicine",
    "S": "STEM",
    "T": "STEM",
    "U": "STEM",
    "V": "STEM",
    "Z": "Social Sciences",
}

LCC_TOP_CLASSIFICATION = {
    "A": "General Works",
    "B": "Philosophy, Psychology, Religion",
    "C": "Auxiliary Sciences of History",
    "D": "World History",
    "E": "History of the Americas",
    "F": "History of the Americas",
    "G": "Geography, Anthropology, Recreation",
    "H": "Social Sciences",
    "J": "Political Science",
    "K": "Law",
    "L": "Education",
    "M": "Music and Books on Music",
    "N": "Fine Arts",
    "P": "Language and Literature",
    "Q": "Science",
    "R": "Medicine",
    "S": "Agriculture",
    "T": "Technology",
    "U": "Military Science",
    "V": "Naval Science",
    "Z": "Bibliography. Library Science. Information Resources (General)",
}

LCC_CLASSIFICATION = {
    "A": "General Works",
    "AC": "Collections, Series, Collected works",
    "AE": "Encyclopedias",
    "AG": "Dictionaries and other general reference works",
    "AI": "Indexes",
    "AM": "Museums, Collectors and collecting",
    "AN": "Newspapers",
    "AP": "Periodicals",
    "AS": "Academies and learned societies",
    "AY": "Yearbooks, Almanacs, Directories",
    "AZ": "History of scholarship and learning",
    "B": "Philosophy (General)",
    "BC": "Logic",
    "BD": "Speculative philosophy",
    "BF": "Psychology",
    "BH": "Aesthetics",
    "BJ": "Ethics",
    "BL": "Religions, Mythology, Rationalism",
    "BM": "Judaism",
    "BP": "Islam, Bahaism, Theosophy, etc.",
    "BQ": "Buddhism",
    "BR": "Christianity",
    "BS": "The Bible",
    "BT": "Doctrinal Theology",
    "BV": "Practical Theology",
    "BX": "Christian Denominations",
    "C": "Auxiliary Sciences of History (General)",
    "CB": "History of Civilization",
    "CC": "Archaeology",
    "CD": "Diplomatics, Archives, Seals",
    "CE": "Technical Chronology, Calendar",
    "CJ": "Numismatics",
    "CN": "Inscriptions, Epigraphy",
    "CR": "Heraldry",
    "CS": "Genealogy",
    "CT": "Biography",
    "D": "History (General)",
    "DA": "Great Britain",
    "DAW": "Central Europe",
    "DB": "Austria, Liechtenstein, Hungary, Czechoslovakia",
    "DC": "France, Andorra, Monaco",
    "DD": "Germany",
    "DE": "Greco-Roman World",
    "DF": "Greece",
    "DG": "Italy, Malta",
    "DH": "Low Countries, Benelux Countries",
    "DJ": "Netherlands (Holland)",
    "DJK": "Eastern Europe (General)",
    "DK": "Russia, Soviet Union, Former Soviet Republics, Poland",
    "DL": "Norhtern Europe, Scandinavia",
    "DP": "Spain, Portugal",
    "DQ": "Switzerland",
    "DR": "Balkan Peninsula",
    "DS": "Asia",
    "DT": "Africa",
    "DU": "Oceania (South Seas)",
    "DX": "Romanies",
    "E": "History of the Americas",
    "F": "History of the Americas",
    "G": "Geography (General), Atlases, Maps",
    "GA": "Mathematical geography, Cartography",
    "GB": "Physical geography",
    "GC": "Oceanography",
    "GE": "Environmental Sciences",
    "GF": "Human Ecology",
    "GN": "Anthropology",
    "GR": "Folklore",
    "GT": "Manners and customs",
    "GV": "Recreation, Leisure",
    "H": "Social Sciences (General)",
    "HA": "Statistics",
    "HB": "Economic theory, Demography",
    "HC": "Economic history and conditions",
    "HD": "Industries, Land use, Labor",
    "HE": "Transportation and communications",
    "HF": "Commerce",
    "HG": "Finance",
    "HJ": "Public finance",
    "HM": "Sociology (General)",
    "HN": "Social history and conditions, Social problems, Social reform",
    "HQ": "The family, Marriage, Women",
    "HS": "Societies: secret, benevolent, etc.",
    "HT": "Communities, Classes, Races",
    "HV": "Social pathology, Social and public welfare, Criminology",
    "HX": "Socialism, Communism, Anarchism",
    "J": "General legislative and executive papers",
    "JA": "Political Science (General)",
    "JC": "Political theory",
    "JF": "Pol. inst. & pub. admin",
    "JJ": "Pol. inst. & pub. admin (North America)",
    "JK": "Pol. inst. & pub. admin (United States)",
    "JL": "Pol. inst. & pub. admin (Canada, Latin America, etc.)",
    "JN": "Pol. inst. & pub. admin (Europe)",
    "JQ": "Pol. inst. & pub. admin (Asia, Africa, Australia, Pacific Area, etc.)",
    "JS": "Local government, Municipal government",
    "JV": "Colonies and colonization, Emigration and immigration, International migration",
    "JX": "International law",
    "JZ": "International relations",
    "K": "Law in general. Comparative and uniform law. Jurisprudence",
    "KB": "Religious law in general. Comparative religious law. Jurisprudence",
    "KBP": "Islamic law",
    "KBR": "History of canon law",
    "KBS": "Canon law of Eastern churches",
    "KBT": "Canon law of Eastern Rite Churches in communion with the Holy See of Rome",
    "KBX": "Canonical collections. Sources",
    "KBM": "Jewish law",
    "KC": "Jurisprudence",
    "KF": "Law of the United States",
    "KG": "Law of Latin America and the Caribbean. Spanish America",
    "KH": "Law of Latin America and the Caribbean. Brazil",
    "KJ-KKZ": "Law of Europe",
    "KL-KWX": "Law of Asia and Eurasia, Africa, Pacific Area, and Antarctica",
    "KZ": "Law of nations",
    "L": "Education (General)",
    "LA": "History of education",
    "LB": "Theory and practice of education",
    "LC": "Special aspects of education",
    "LD": "Individual institutions – United States",
    "LE": "Individual institutions – America outside the United States",
    "LF": "Individual institutions – Europe",
    "LG": "Individual institutions – Asia, Africa, Indian Ocean islands, Australia, New Zealand, Pacific islands",
    "LH": "College and school magazines and papers",
    "LJ": "Student fraternities and societies, United States",
    "LT": "Textbooks",
    "M": "Music",
    "ML": "Literature on music",
    "MT": "Instruction and study",
    "N": "Fine Arts",
    "NA": "Architecture",
    "NB": "Sculpture",
    "NC": "Drawing. Design. Illustration",
    "ND": "Painting",
    "NE": "Print media",
    "NK": "Decorative arts",
    "NX": "Arts in general",
    "P": "Philology. Linguistics",
    "PA": "Classical languages and literature",
    "PB": "Modern languages. Celtic languages",
    "PC": "Romanic languages",
    "PD": "Germanic languages. Scandinavian languages",
    "PE": "English language",
    "PF": "West Germanic languages",
    "PG": "Slavic. Baltic. Albanian languages",
    "PH": "Uralic languages. Basque language",
    "PJ": "Oriental languages and literatures",
    "PK": "Indo-Iranian languages and literatures",
    "PL": "Languages and literatures of Eastern Asia, Africa, Oceania",
    "PM": "Hyperborean, Indian, and artificial languages",
    "PN": "Literature (General)",
    "PQ": "Romance literatures",
    "PR": "English literature",
    "PS": "American literature",
    "PT": "Germanic literature",
    "PZ": "Fiction and juvenile belles lettres",
    "Q": "Science (General)",
    "QA": "Mathematics",
    "QB": "Astronomy",
    "QC": "Physics",
    "QD": "Chemistry",
    "QE": "Geology",
    "QH": "Natural history. Biology",
    "QK": "Botany",
    "QL": "Zoology",
    "QM": "Human anatomy",
    "QP": "Physiology",
    "QR": "Microbiology",
    "R": "Medicine (General)",
    "RA": "Public aspects of medicine",
    "RB": "Pathology",
    "RC": "Internal medicine",
    "RD": "Surgery",
    "RE": "Ophthalmology",
    "RF": "Otorhinolaryngology",
    "RG": "Gynecology and obstetrics",
    "RJ": "Pediatrics",
    "RK": "Dentistry",
    "RL": "Dermatology",
    "RM": "Therapeutics. Pharmacology",
    "RS": "Pharmacy and materia medica",
    "RT": "Nursing",
    "RV": "Botanic, Thomsonian, and eclectic medicine",
    "RX": "Homeopathy",
    "RZ": "Other systems of medicine",
    "S": "Agriculture (General)",
    "SB": "Plant culture",
    "SD": "Forestry",
    "SF": "Animal culture",
    "SH": "Aquaculture. Fisheries. Angling",
    "SK": "Hunting sports",
    "T": "Technology (General)",
    "TA": "Engineering (General). Civil engineering",
    "TC": "Hydraulic engineering. Ocean engineering",
    "TD": "Environmental technology. Sanitary engineering",
    "TE": "Highway engineering. Roads and pavements",
    "TF": "Railroad engineering and operation",
    "TG": "Bridges",
    "TH": "Building construction",
    "TJ": "Mechanical engineering and machinery",
    "TK": "Electrical engineering. Electronics. Nuclear engineering",
    "TL": "Motor vehicles. Aeronautics. Astronautics",
    "TN": "Mining engineering. Metallurgy",
    "TP": "Chemical technology",
    "TR": "Photography",
    "TS": "Manufacturing engineering. Mass production",
    "TT": "Handicrafts. Arts and crafts",
    "TX": "Home economics",
    "U": "Military science (General)",
    "UA": "Armies: Organization, distribution, military situation",
    "UB": "Military administration",
    "UC": "Maintenance and transportation",
    "UD": "Infantry",
    "UE": "Cavalry. Armor",
    "UF": "Artillery",
    "UG": "Military engineering. Air forces",
    "UH": "Other services",
    "V": "Naval science (General)",
    "VA": "Navies: Organization, distribution, naval situation",
    "VB": "Naval administration",
    "VC": "Maintenance and transportation",
    "VD": "Naval seamen",
    "VE": "Marines",
    "VF": "Naval ordnance",
    "VG": "Minor services of navies",
    "VK": "Navigation. Merchant marine",
    "VM": "Naval architecture. Shipbuilding. Marine engineering",
    "Z": "Bibliography. Library science. Information resources (General)",
    "ZA": "Information resources (General)",
}
